---
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

executors:
  node-docker:
    parameters:
      node-version:
        # renovate datasource=node-version depName=node
        default: 20.11.1
        type: string
    docker:
      - image: cimg/node:<<parameters.node-version>>
    resource_class: small

jobs:
  randomix-test:
    executor: node-docker
    working_directory: ~/randomix
    steps:
      - attach_workspace:
          at: ~/randomix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v2-randomix-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v2-randomix-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Test
          command: |
            npm test

  checkout:
    executor: node-docker
    working_directory: ~/randomix
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/randomix
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - randomix-test:
          requires:
            - checkout